# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kuuki_remote_pb2 as kuuki__remote__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kuuki_remote_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteControlStub(object):
    """---------------------------------------------------------------- 服务

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/GetInfo',
                request_serializer=kuuki__remote__pb2.Empty.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Info.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/Ping',
                request_serializer=kuuki__remote__pb2.Empty.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.Screenshot = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/Screenshot',
                request_serializer=kuuki__remote__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Image.FromString,
                _registered_method=True)
        self.StreamScreenshots = channel.unary_stream(
                '/kuuki.remote.v1.RemoteControl/StreamScreenshots',
                request_serializer=kuuki__remote__pb2.StreamScreenshotsRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Image.FromString,
                _registered_method=True)
        self.GetMonitors = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/GetMonitors',
                request_serializer=kuuki__remote__pb2.Empty.SerializeToString,
                response_deserializer=kuuki__remote__pb2.MonitorList.FromString,
                _registered_method=True)
        self.GetMousePosition = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/GetMousePosition',
                request_serializer=kuuki__remote__pb2.Empty.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Point.FromString,
                _registered_method=True)
        self.MoveMouse = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/MoveMouse',
                request_serializer=kuuki__remote__pb2.MoveMouseRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.MoveMouseRelative = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/MoveMouseRelative',
                request_serializer=kuuki__remote__pb2.MoveMouseRelativeRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.ClickMouse = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/ClickMouse',
                request_serializer=kuuki__remote__pb2.ClickMouseRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.MouseDown = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/MouseDown',
                request_serializer=kuuki__remote__pb2.MouseButtonRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.MouseUp = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/MouseUp',
                request_serializer=kuuki__remote__pb2.MouseButtonRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.Scroll = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/Scroll',
                request_serializer=kuuki__remote__pb2.ScrollRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.Drag = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/Drag',
                request_serializer=kuuki__remote__pb2.DragRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/TypeText',
                request_serializer=kuuki__remote__pb2.TypeTextRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.PressKey = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/PressKey',
                request_serializer=kuuki__remote__pb2.KeyRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.Hotkey = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/Hotkey',
                request_serializer=kuuki__remote__pb2.HotkeyRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.PasteText = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/PasteText',
                request_serializer=kuuki__remote__pb2.PasteTextRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.Ack.FromString,
                _registered_method=True)
        self.CheckKeys = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/CheckKeys',
                request_serializer=kuuki__remote__pb2.KeyCheckRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.KeyCheckReply.FromString,
                _registered_method=True)
        self.SendKuukiMessage = channel.unary_unary(
                '/kuuki.remote.v1.RemoteControl/SendKuukiMessage',
                request_serializer=kuuki__remote__pb2.KuukiMessageRequest.SerializeToString,
                response_deserializer=kuuki__remote__pb2.KuukiMessageReply.FromString,
                _registered_method=True)


class RemoteControlServicer(object):
    """---------------------------------------------------------------- 服务

    """

    def GetInfo(self, request, context):
        """元信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """截屏
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScreenshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMousePosition(self, request, context):
        """鼠标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveMouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveMouseRelative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickMouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MouseDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MouseUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """键盘
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PressKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hotkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PasteText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckKeys(self, request, context):
        """预检: 这些键在当前键盘布局里能不能发 (不实际按键)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendKuukiMessage(self, request, context):
        """空气鼠标老协议透传 (姿态数据 / 鼠标键 / 文本)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=kuuki__remote__pb2.Empty.FromString,
                    response_serializer=kuuki__remote__pb2.Info.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=kuuki__remote__pb2.Empty.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=kuuki__remote__pb2.ScreenshotRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Image.SerializeToString,
            ),
            'StreamScreenshots': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScreenshots,
                    request_deserializer=kuuki__remote__pb2.StreamScreenshotsRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Image.SerializeToString,
            ),
            'GetMonitors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitors,
                    request_deserializer=kuuki__remote__pb2.Empty.FromString,
                    response_serializer=kuuki__remote__pb2.MonitorList.SerializeToString,
            ),
            'GetMousePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMousePosition,
                    request_deserializer=kuuki__remote__pb2.Empty.FromString,
                    response_serializer=kuuki__remote__pb2.Point.SerializeToString,
            ),
            'MoveMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveMouse,
                    request_deserializer=kuuki__remote__pb2.MoveMouseRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'MoveMouseRelative': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveMouseRelative,
                    request_deserializer=kuuki__remote__pb2.MoveMouseRelativeRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'ClickMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickMouse,
                    request_deserializer=kuuki__remote__pb2.ClickMouseRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'MouseDown': grpc.unary_unary_rpc_method_handler(
                    servicer.MouseDown,
                    request_deserializer=kuuki__remote__pb2.MouseButtonRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'MouseUp': grpc.unary_unary_rpc_method_handler(
                    servicer.MouseUp,
                    request_deserializer=kuuki__remote__pb2.MouseButtonRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'Scroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Scroll,
                    request_deserializer=kuuki__remote__pb2.ScrollRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'Drag': grpc.unary_unary_rpc_method_handler(
                    servicer.Drag,
                    request_deserializer=kuuki__remote__pb2.DragRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=kuuki__remote__pb2.TypeTextRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'PressKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PressKey,
                    request_deserializer=kuuki__remote__pb2.KeyRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'Hotkey': grpc.unary_unary_rpc_method_handler(
                    servicer.Hotkey,
                    request_deserializer=kuuki__remote__pb2.HotkeyRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'PasteText': grpc.unary_unary_rpc_method_handler(
                    servicer.PasteText,
                    request_deserializer=kuuki__remote__pb2.PasteTextRequest.FromString,
                    response_serializer=kuuki__remote__pb2.Ack.SerializeToString,
            ),
            'CheckKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckKeys,
                    request_deserializer=kuuki__remote__pb2.KeyCheckRequest.FromString,
                    response_serializer=kuuki__remote__pb2.KeyCheckReply.SerializeToString,
            ),
            'SendKuukiMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendKuukiMessage,
                    request_deserializer=kuuki__remote__pb2.KuukiMessageRequest.FromString,
                    response_serializer=kuuki__remote__pb2.KuukiMessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuuki.remote.v1.RemoteControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuuki.remote.v1.RemoteControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteControl(object):
    """---------------------------------------------------------------- 服务

    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/GetInfo',
            kuuki__remote__pb2.Empty.SerializeToString,
            kuuki__remote__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/Ping',
            kuuki__remote__pb2.Empty.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/Screenshot',
            kuuki__remote__pb2.ScreenshotRequest.SerializeToString,
            kuuki__remote__pb2.Image.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScreenshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/StreamScreenshots',
            kuuki__remote__pb2.StreamScreenshotsRequest.SerializeToString,
            kuuki__remote__pb2.Image.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/GetMonitors',
            kuuki__remote__pb2.Empty.SerializeToString,
            kuuki__remote__pb2.MonitorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMousePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/GetMousePosition',
            kuuki__remote__pb2.Empty.SerializeToString,
            kuuki__remote__pb2.Point.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/MoveMouse',
            kuuki__remote__pb2.MoveMouseRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveMouseRelative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/MoveMouseRelative',
            kuuki__remote__pb2.MoveMouseRelativeRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/ClickMouse',
            kuuki__remote__pb2.ClickMouseRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MouseDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/MouseDown',
            kuuki__remote__pb2.MouseButtonRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MouseUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/MouseUp',
            kuuki__remote__pb2.MouseButtonRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/Scroll',
            kuuki__remote__pb2.ScrollRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/Drag',
            kuuki__remote__pb2.DragRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/TypeText',
            kuuki__remote__pb2.TypeTextRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PressKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/PressKey',
            kuuki__remote__pb2.KeyRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hotkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/Hotkey',
            kuuki__remote__pb2.HotkeyRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PasteText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/PasteText',
            kuuki__remote__pb2.PasteTextRequest.SerializeToString,
            kuuki__remote__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/CheckKeys',
            kuuki__remote__pb2.KeyCheckRequest.SerializeToString,
            kuuki__remote__pb2.KeyCheckReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendKuukiMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuuki.remote.v1.RemoteControl/SendKuukiMessage',
            kuuki__remote__pb2.KuukiMessageRequest.SerializeToString,
            kuuki__remote__pb2.KuukiMessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
